name: MobPlugin
main: nukkitcoders.mobplugin.MobPlugin
version: "1.26.3-PNX"
api: ["2.0.0"]
author: kniffo80, matt404, augesrob, PetteriM1, PikyCZ, zzz1999, SergeyDertan
description: Entity AI & autospawn plugin for NukkitX servers
website: https://nukkitx.com/resources/mobplugin.3/
load: STARTUP

commands:
 mob:
  description: Mob plugin main command
  usage: /mob
  permission: mobplugin.command

permissions:
 mobplugin.command:
  description: ""
  default: op
